const CREATE_NEW_COLUMN = "CREATE_NEW_COLUMN";
const UPDATE_COLUMN = "UPDATE_COLUMN";
const DELETE_COLUMN = "DELETE_COLUMN";
const INIT_SELECTED_COLUMN = "INIT_SELECTED_COLUMN";
const CLEAR_SELECTED_COLUMN = "CLEAR_SELECTED_COLUMN";
export { CREATE_NEW_COLUMN, DELETE_COLUMN, UPDATE_COLUMN, INIT_SELECTED_COLUMN, CLEAR_SELECTED_COLUMN };